### ISSUE TITLE
Unnecessary space in template method 

### ISSUE THREAD

**Issue by ald890** [lukawski/polymer-transpiler#5]
Space before ` produce problems for lit-html syntax.

```
static get template () {
        return Polymer.html `
```

**Comment by mstreich** [comment]
fixed in #9

**Comment by ald890** [comment]
Nice, it looked like the project had died and the author completely had lost his motivation.

**Comment by mstreich** [comment]
Well, it seems that project actually died and author certainly lost his motivation.

**Comment by pstachula-dev** [comment]
Live fast, die young. The next young artist with little enthusiasm. nah
